apiVersion: v1
kind: Namespace
metadata:
  name: probler-box
  labels:
    name: probler-box

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: probler-box
  name: probler-box
  labels:
    app: probler-box
spec:
  #serviceName: probler-box
  #replicas: 3
  selector:
    matchLabels:
      app: probler-box
  template:
    metadata:
      labels:
        app: probler-box
    spec:
      containers:
        - name: probler-box
          image: saichler/probler-inv-box:latest
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: hdata
              mountPath: /data
      volumes:
        - name: hdata
          hostPath:
            path: /data
            type: DirectoryOrCreate
