apiVersion: v1
kind: Namespace
metadata:
  name: probler-logs
  labels:
    name: probler-logs

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: probler-logs
  name: probler-logs
  labels:
    app: probler-logs
spec:
  selector:
    matchLabels:
      app: probler-logs
  template:
    metadata:
      labels:
        app: probler-logs
    spec:
      hostNetwork: true
      containers:
        - name: probler-logs
          image: saichler/logs-vnet:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 12888
          volumeMounts:
            - name: hdata
              mountPath: /data
      volumes:
        - name: hdata
          hostPath:
            path: /data
            type: DirectoryOrCreate