apiVersion: v1
kind: Namespace
metadata:
  name: probler-topo
  labels:
    name: probler-topo

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: probler-topo
  name: probler-topo
  labels:
    app: probler-topo
spec:
  serviceName: probler-topo
  replicas: 1
  selector:
    matchLabels:
      app: probler-topo
  template:
    metadata:
      labels:
        app: probler-topo
    spec:
      containers:
        - name: probler-topo
          image: saichler/probler-topo:latest
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
